apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - postgres-api-cluster.yaml
  - postgres-credentials.yaml
  # MANUAL: Uncomment after configuring backup credentials
  # - backup-credentials-MANUAL.yaml
