apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: keycloak-realm
    namespace: share-app
    files:
      - realm-export.json=../../../base/keycloak/realm-dev.json

resources:
  - secrets.yaml

patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: keycloak
