apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# External Secrets - Production
# Installs External Secrets Operator only
# ClusterSecretStore and generators are in individual apps

resources:
  - ../../base
