apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfga
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfga.plv.it.com`)
      kind: Rule
      services:
        - name: openfga
          port: 8080
  tls:
    certResolver: letsencrypt
