apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# OpenFGA Base
# Authorization and fine-grained access control service

resources:
  - deployment.yaml
  - postgres-openfga-cluster.yaml
  - secrets.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: openfga
