apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# OpenFGA Base
# Authorization and fine-grained access control service

resources:
  - namespace.yaml
  - helmrepository.yaml
  - postgres-openfga-cluster.yaml
  - helmrelease.yaml

namespace: openfga

configurations:
  - kustomizeconfig.yaml
