apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: keycloak
  - path: realm-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: keycloak-realm
