apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/openfga
  - cluster-secret-store.yaml
  - secret-generator.yaml
  - external-secret.yaml
  - openfga-db-uri-secret.yaml
  - postgres-openfga-cluster.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
