apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.plv.it.com`)
      kind: Rule
      services:
        - name: keycloak-keycloak-keycloakx-http
          port: 80
  tls:
    certResolver: letsencrypt
