apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret-generator-job.yaml
  - secrets.yaml
  - helmrelease.yaml
  - ingressroute.yaml

namespace: keycloak