apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- communities-sync.yaml
- image-automation/image-repositories.yaml
- image-automation/image-policies.yaml
- image-automation/image-update-automation.yaml
